<?php

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_landing-page',
        'title' => 'Landing page',
        'fields' => array (
            array (
                'key' => 'field_56c2f21b2d401',
                'label' => 'Page items',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56c2f47fd74d0',
                'label' => 'Contact number',
                'name' => 'contact_number',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f27074b6a',
                'label' => 'Heading 1',
                'name' => 'message_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f32d74b6b',
                'label' => 'Quote button 1',
                'name' => 'quote_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f3ea74b6d',
                'label' => 'Heading 2',
                'name' => 'message_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f3f274b6e',
                'label' => 'Quote button 2',
                'name' => 'quote_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f2242d402',
                'label' => 'Testimonials',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56c2f5078842f',
                'label' => 'Testimonial 1 author',
                'name' => 'testimonial_author_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f52f88431',
                'label' => 'Testimonial 1 content',
                'name' => 'testimonial_content_1',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_56c2f52688430',
                'label' => 'Testimonial 2 author',
                'name' => 'testimonial_author_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f54b88432',
                'label' => 'Testimonial 2 content',
                'name' => 'testimonial_content_2',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_56c2f2322d403',
                'label' => 'Services',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56c2f6945baf5',
                'label' => 'Services heading',
                'name' => 'services_title',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f6b05baf6',
                'label' => 'Services description',
                'name' => 'services_description',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_56c2f7061b88a',
                'label' => 'Service 1 heading',
                'name' => 'service_heading_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f74f1b88b',
                'label' => 'Service 1 description',
                'name' => 'service_content_1',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_56c2f77d1b88c',
                'label' => 'Service 2 heading',
                'name' => 'service_heading_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f7c74adbd',
                'label' => 'Service 2 description',
                'name' => 'service_content_2',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_56c2f79a1b88d',
                'label' => 'Service 3 heading',
                'name' => 'service_heading_3',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f7f54adbe',
                'label' => 'Service 3 description',
                'name' => 'service_content_3',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_56c2f7b01b88e',
                'label' => 'Service 4 heading',
                'name' => 'service_heading_4',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56c2f7fd4adbf',
                'label' => 'Service 4 description',
                'name' => 'service_content_4',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '11',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
}
